name: üîó ÊâãÂä®ÈÉ®ÁΩ≤ GitPage

on: 
    workflow_dispatch:
  
# ËÆæÁΩÆ GITHUB_TOKEN ÁöÑÊùÉÈôêÔºå‰ª•ÂÖÅËÆ∏ÈÉ®ÁΩ≤Âà∞ GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # ÊûÑÂª∫Â∑•‰Ωú
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show the timezone
        run: |
           date 
           uname -r
           free -hg
           pwd
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # lastUpdated ÈúÄË¶Å
          submodules: recursive
      - name: Build inside FreeBSD VM
        uses: vmactions/freebsd-vm@v1.3.8
        with:
          release: "15.0"
          arch: x86_64
          sync-time: true
          mem: 10240
          run: |
            pkg update -f 
            ls -l /home/runner/work/FreeBSD-Ask.github.io/FreeBSD-Ask.github.io/
            pwd
            echo "222" > 1.txt
            cp 1.txt /home/runner/work/FreeBSD-Ask.github.io/FreeBSD-Ask.github.io/docs/
            
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Â§çÂà∂È¶ñÈ°µ
        run:  |
          ls /home/runner/work/FreeBSD-Ask.github.io/FreeBSD-Ask.github.io
          pwd

        
